import type { Metadata } from 'next';
import './globals.css';
import { Inter, Covered_By_Your_Grace } from 'next/font/google';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';


const inter = Inter({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-inter',
});

const coveredByYourGrace = Covered_By_Your_Grace({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-covered-by-your-grace',
});

export const metadata: Metadata = {
  title: 'PostPilot',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className} ${inter.variable} ${coveredByYourGrace.variable} flex min-h-screen flex-col w-full`}
      >
        <Header /> 
        <main className="flex flex-1 flex-col w-full overflow-hidden">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
